# Valores por defecto para personalización
color_barra_adaion: "#FF5733"      # Naranja para trabajo
color_fuente_adaion: "#FFFFFF"
color_barra_home: "#33C1FF"        # Azul para personal
color_fuente_home: "#FFFFFF"

# Paquetes por distribución
packages:
  ubuntu:
    - build-essential
    - zsh
    - git
    - curl
    - wget
    - unzip
    - fzf
    - ripgrep
    - bat
    - fd-find
    - python3
    - python3-venv
    - python3-pip
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release
    - jq
    - ripgrep
    - fzf
    - tldr
    - httpie
    - code
  arch:
    - accountsservice
    - accountsservice
    - alsa-firmware
    - alsa-plugins
    - alsa-utils
    - amd-ucode
    - ark
    - aspell
    - b43-fwcutter
    - base
    - base-devel
    - bash-completion
    - bat
    - bind
    - bitwarden-cli
    - bluedevil
    - bluez
    - bluez-utils
    - brave-bin
    - breeze-gtk
    - btrfs-progs
    - cantarell-fonts
    - chezmoi
    - cryptsetup
    - device-mapper
    - dialog
    - diffutils
    - dmidecode
    - dmraid
    - dnsmasq
    - docker
    - docker-compose
    - dolphin
    - dolphin-plugins
    - dosfstools
    - downgrade
    - dracut
    - duf
    - e2fsprogs
    - efibootmgr
    - efitools
    - endeavouros-branding
    - endeavouros-keyring
    - endeavouros-konsole-colors
    - endeavouros-mirrorlist
    - eos-apps-info
    - eos-breeze-sddm
    - eos-dracut
    - eos-hooks
    - eos-log-tool
    - eos-packagelist
    - eos-quickstart
    - eos-rankmirrors
    - eos-settings-plasma
    - ethtool
    - ex-vi-compat
    - exfatprogs
    - eza
    - f2fs-tools
    - ffmpegthumbs
    - firefox
    - firewalld
    - fwupd
    - git
    - git-delta
    - glances
    - grub
    - gst-libav
    - gst-plugin-pipewire
    - gst-plugins-bad
    - gst-plugins-ugly
    - gwenview
    - haruna
    - haveged
    - hdparm
    - helix
    - hwdetect
    - hwinfo
    - inetutils
    - inxi
    - iptables-nft
    - iwd
    - jfsutils
    - kate
    - kcalc
    - kde-cli-tools
    - kde-gtk-config
    - kdeconnect
    - kdegraphics-thumbnailers
    - kdenetwork-filesharing
    - kdeplasma-addons
    - kgamma
    - kimageformats
    - kinfocenter
    - kio-admin
    - kio-extras
    - kio-fuse
    - konsole
    - kscreen
    - kwallet-pam
    - kwayland-integration
    - less
    - libappindicator
    - libdvdcss
    - libgsf
    - libopenraw
    - linux
    - linux-firmware
    - linux-headers
    - linux-lts
    - linux-lts-headers
    - logrotate
    - lsb-release
    - lsscsi
    - lvm2
    - man-db
    - man-pages
    - mdadm
    - meld
    - mesa-utils
    - mkinitcpio
    - modemmanager
    - mtools
    - nano
    - nano-syntax-highlighting
    - neovim
    - netctl
    - networkmanager
    - networkmanager-openconnect
    - networkmanager-openvpn
    - nfs-utils
    - nilfs-utils
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra
    - nss-mdns
    - ntfs-3g
    - ntp
    - nvidia-hook
    - nvidia-inst
    - nvidia-open
    - nvidia-open-lts
    - okular
    - openssh
    - os-prober
    - pacman-contrib
    - pavucontrol
    - perl
    - pipewire-alsa
    - pipewire-jack
    - pipewire-pulse
    - pkgfile
    - plasma-browser-integration
    - plasma-desktop
    - plasma-disks
    - plasma-firewall
    - plasma-keyboard
    - plasma-nm
    - plasma-pa
    - plasma-systemmonitor
    - plasma-workspace
    - plasma-x11-session
    - plocate
    - plymouth
    - poppler-glib
    - power-profiles-daemon
    - powerdevil
    - print-manager
    - python
    - python-defusedxml
    - python-jinja
    - python-packaging
    - python-pyqt6
    - qt6-imageformats
    - rebuild-detector
    - reflector
    - reflector-simple
    - rsync
    - rtkit
    - s-nail
    - sddm-kcm
    - sg3_utils
    - smartmontools
    - sof-firmware
    - spectacle
    - starship
    - sudo
    - switcheroo-control
    - sysfsutils
    - systemd-sysvcompat
    - texinfo
    - tk
    - tldr
    - ttf-bitstream-vera
    - ttf-cascadia-code-nerd
    - ttf-dejavu
    - ttf-dejavu-nerd
    - ttf-firacode-nerd
    - ttf-hack-nerd
    - ttf-iosevka-nerd
    - ttf-jetbrains-mono-nerd
    - ttf-liberation
    - ttf-opensans
    - unrar
    - unzip
    - upower
    - usb_modeswitch
    - usbutils
    - visual-studio-code-bin
    - warp-terminal
    - welcome
    - wget
    - which
    - whois
    - wireless-regdb
    - wireplumber
    - woeusb-ng
    - wpa_supplicant
    - xdg-desktop-portal-kde
    - xdg-user-dirs
    - xdg-utils
    - xf86-input-libinput
    - xfsprogs
    - xl2tpd
    - xorg-server
    - xorg-xdpyinfo
    - xorg-xinit
    - xorg-xinput
    - xorg-xkill
    - xorg-xrandr
    - xsettingsd
    - xterm
    - yakuake
    - yay
    - zoxide
    - zsh
    - zsh-completions
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - fzf
    - ripgrep
    - tldr
    - httpie
    - lazygit
