# Default shell placeholder (configured by Gentleman.Dots installer)
set -g default-command "/home/linuxbrew/.linuxbrew/bin/zsh"
set -g default-shell "/home/linuxbrew/.linuxbrew/bin/zsh"

# Carga TPM
set -g @plugin 'tmux-plugins/tpm'

# Tested options for TMUX compatibility
set -g @plugin 'tmux-plugins/tmux-sensible'

# Clipboard management
set -g @plugin 'tmux-plugins/tmux-yank'

# Tmux Navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

# Tmux Resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Which Key
set -g @plugin 'alexwforsythe/tmux-which-key'

# Floating window
bind-key -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  # open in the same directory of the current pane
  display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}

# Tema Kanagawa
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'dragon'
set -g @kanagawa-plugins "git cpu-usage ram-usage"
set -g @kanagawa-ignore-window-colors true

# --- terminal & key handling ---
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

set -s extended-keys off

# Modo vim
set -g mode-keys vi
if-shell 'uname | grep -q Darwin' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip"'

# Keymaps
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Window / Tab management
bind c new-window -c "#{pane_current_path}"
bind q confirm-before -p "Close window #I:#W? (y/n)" kill-window
bind Tab last-window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 last-window

unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"

# Mouse support
set -g mouse on

# Status bar position
set -g status-position top
set -g status-justify left
set -g status-left-length 20
set -g status-right-length 80
setw -g window-status-separator " "
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #[bold]▍ #I:#W #[default]"

# Kill all sessions except current
bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"

# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Fix index
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g allow-rename off
setw -g automatic-rename on
setw -g automatic-rename-format "#{b:pane_current_path}:#{pane_current_command}"

# TPM init
run '~/.tmux/plugins/tpm/tpm'
